{
  "hash": "be1534a40d1bbf4120e8432cd090b943",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\ndescription: \"Measuring uncertainty in American Community Survey data\"\nauthor: Michael Pincus\ndate: 09-04-2026\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\neditor: \n  markdown: \n    wrap: 72\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate\ndrawn from a sample, not a count. That means every number comes with a\nmargin of error — a statement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n**In this analysis, I look at total commuters across counties in\nConnecticut, and ask which communities we measure most and least\nreliably. As Connecticut features a large commuter region to New York in\nthe southwestern part of the state, I am curious about the general\npatterns across Connecticut and where census estimates tend to be more\nreliable.**\n\n## Choosing what to measure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"CT\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B08303_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9 5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                                             variable estimate   moe\n  <chr> <chr>                                            <chr>       <dbl> <dbl>\n1 09110 Capitol Planning Region, Connecticut             B08303_…   411729  3849\n2 09120 Greater Bridgeport Planning Region, Connecticut  B08303_…   136932  2110\n3 09130 Lower Connecticut River Valley Planning Region,… B08303_…    78097  1309\n4 09140 Naugatuck Valley Planning Region, Connecticut    B08303_…   198589  2586\n5 09150 Northeastern Connecticut Planning Region, Conne… B08303_…    42707  1095\n6 09160 Northwest Hills Planning Region, Connecticut     B08303_…    49420  1043\n```\n\n\n:::\n:::\n\n\n**My data has 9 rows, matching the 9 census-used planning regions in the\nstate of Connecticut.**\n\n------------------------------------------------------------------------\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an\nestimate of 20,000 than for an estimate of 200,000. To compare across\nplaces, we need it as a percentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 4\n  NAME                                                    estimate   moe moe_pct\n  <chr>                                                      <dbl> <dbl>   <dbl>\n1 Northeastern Connecticut Planning Region, Connecticut      42707  1095   2.56 \n2 Northwest Hills Planning Region, Connecticut               49420  1043   2.11 \n3 Lower Connecticut River Valley Planning Region, Connec…    78097  1309   1.68 \n4 Greater Bridgeport Planning Region, Connecticut           136932  2110   1.54 \n5 Southeastern Connecticut Planning Region, Connecticut     122762  1814   1.48 \n6 Western Connecticut Planning Region, Connecticut          256479  3731   1.45 \n7 Naugatuck Valley Planning Region, Connecticut             198589  2586   1.30 \n8 South Central Connecticut Planning Region, Connecticut    245723  2876   1.17 \n9 Capitol Planning Region, Connecticut                      411729  3849   0.935\n```\n\n\n:::\n:::\n\n\n**The Northeastern Connecticut Planning Region has the largest `moe_pct`\nrelative to its estimate, measuring at about 2.6%.**\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 1  ~ \"High confidence\",\n    moe_pct < 2 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence     1\n2 Low confidence      2\n3 Moderate            6\n```\n\n\n:::\n:::\n\n\nAs the percent margin of error for all 9 planning regions of Connecticut\nfell well into the original \\<5% cutoff for `High confidence`, the\ncategories were adjusted so that `High confidence` represents a margin\nof error of \\<1%, `Moderate` represents a margin of error of \\<2%, and\n`Low confidence` represents a margin of error of \\>2%.\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the\nsame row. That means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                                          myvarE myvarM   popE  popM\n  <chr> <chr>                                          <dbl>  <dbl>  <dbl> <dbl>\n1 09110 Capitol Planning Region, Connecticut          411729   3849 969029    NA\n2 09120 Greater Bridgeport Planning Region, Connecti… 136932   2110 326296    NA\n3 09130 Lower Connecticut River Valley Planning Regi…  78097   1309 174983    NA\n4 09140 Naugatuck Valley Planning Region, Connecticut 198589   2586 452303    NA\n5 09150 Northeastern Connecticut Planning Region, Co…  42707   1095  95829    NA\n6 09160 Northwest Hills Planning Region, Connecticut   49420   1043 112848    NA\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 1  ~ \"High confidence\",\n    moe_pct < 2 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability\ncategory.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  ) %>%\n  arrange(desc(avg_population))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence          1        969029 \n2 Moderate                 6        403440.\n3 Low confidence           2        104338.\n```\n\n\n:::\n:::\n\n\n**The `avg_population` of high-confidence planning regions are much\nhigher than the `avg_population` of low-confidence planning regions, the\nformer being about 969,029 and the latter being about 104,338.**\n\n## What this means for policy\n\nThrough this exercise, we learned that we know the least about the\nNortheastern Connecticut and the Northeast Hills planning regions. As\nboth of these planning regions feature the lowest populations in the\nstate, they feature the lowest sample sizes and largest percent margin\nof error (\\>2%) in the American Community Survey data set.\n\nIt is important to understand the variability of reliability within the\nACS data set when making policy decisions, as certain planning regions\nwith lower sample sizes may be underrepresented. For example,\ncommunities in the northeastern and northwestern corners of the state\nmay appear to have fewer commuters than in the Hartford region, though\nin reality it may be an artifact of sample size. Poor data literacy in\nthe policy making process could result in a reduction in bus service\nwithin these regions, despite them in reality having a larger need for\npublic transportation than anticipated.\n\n## Plotting Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nplanning_regions <- read_sf('assignments/data/CT_Planning_Regions.geojson')\n\nplanning_regions <- left_join(planning_regions, county_wide, by=c('PlanningRegionFIPS_GEOID'='GEOID'))\n\nplanning_regions<- planning_regions %>%\n  arrange(match(reliability, c(\"High confidence\", \"Moderate\", \"Low confidence\")))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\nreliability_map <- ggplot(planning_regions) +\n  geom_sf(aes(fill=reliability), color='white') +\n  scale_fill_manual(values = c(\"High confidence\" = \"#b71c1c\", \n                               \"Moderate\" = \"#f4977a\", \n                               \"Low confidence\" = \"#fce4de\"),\n                    breaks = c(\"High confidence\", \"Moderate\", \"Low confidence\")) + \n  labs(title='Reliability of Census Estimates', fill=NULL) +\n  theme_void()\n\npop_map <- ggplot(planning_regions) +\n  geom_sf(aes(fill = popE), color = 'white') +\n  scale_fill_distiller(palette = \"Reds\", direction = 1) +\n  labs(title='Population', fill=NULL) + \n  theme_void()\n\nreliability_map + pop_map\n```\n\n::: {.cell-output-display}\n![](assignment2-_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n",
    "supporting": [
      "assignment2-_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}